name: Build PolyTalk APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ensure project (flutter create if missing)
        run: |
          if [ ! -f "android/gradlew" ]; then
            flutter create -t app .
          else
            echo "android present"
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PolyTalk_apk
          path: build/app/outputs/flutter-apk/app-release.apk
